export const MENUITEMS = [
  {
    menutitle: "DASHBOARD",
    Items: [
      {
        path: `dashboard`,
        icon: "ti-home",
        type: "link",
        active: false,
        role: ["admin", "user", "customer service"],
        selected: false,
        title: "Dashboard",
      },
    ],
  },
  {
    menutitle: "Offers & Reservations",
    Items: [
      {
        path: `reservations`,
        icon: "si si-diamond",
        type: "link",
        active: false,
        role: ["admin", "user"],
        selected: false,
        title: "Offers",
      },
      {
        path: `all-packages`,
        icon: "si si-tag",
        type: "link",
        active: false,
        role: ["admin", "user"],
        selected: false,
        title: "Packages",
      },
      {
        path: `all-reserved-packages`,
        icon: "pe-7s-date",
        type: "link",
        active: false,
        role: ["admin", "user"],
        selected: false,
        title: "Reservations",
      },
      {
        path: `create-tour`,
        icon: "si si-note",
        type: "link",
        active: false,
        role: ["admin", "user"],
        selected: false,
        title: "Create Tour",
      },
    ],
  },
  {
    menutitle: "Tour Operator",
    Items: [
      {
        title: "Tours",
        icon: "si si-directions",
        type: "sub",
        active: false,
        role: ["admin", "user"],
        selected: false,
        children: [
          {
            path: `all-tours`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "All tours",
          },
          {
            path: `add-tour`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Add Tour",
          },
        ],
      },

      {
        title: "Drivers",
        icon: "pe-7s-car",
        type: "sub",
        active: false,
        role: ["admin", "user"],
        selected: false,
        children: [
          {
            path: `driver/all`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "All Drivers",
          },
          {
            path: `driver/add`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Add Driver",
          },
        ],
      },
      // {
      //   title: "Tourguides",
      //   icon: "si si-user",
      //   type: "sub",
      //   active: false,
      //   role: ["admin", "user"],
      //   selected: false,
      //   children: [
      //     {
      //       path: `tourguide/all`,
      //       type: "link",
      //       active: false,
      //       role: ["admin", "user"],
      //       selected: false,
      //       title: "All Tourguides",
      //     },
      //     {
      //       path: `tourguide/add`,
      //       type: "link",
      //       active: false,
      //       role: ["admin", "user"],
      //       selected: false,
      //       title: "Add Tourguide",
      //     },
      //   ],
      // },
      {
        title: "Accommodations",
        icon: "fe fe-home",
        type: "sub",
        active: false,
        role: ["admin", "user"],
        selected: false,
        children: [
          {
            path: `accommodation/all`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "All Accommodations",
          },
          {
            path: `accommodation/add`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Add Accommodation",
          },
        ],
      },
    ],
  },
  {
    menutitle: "Website & Landing Pages",
    Items: [
      // {
      //   title: "Website",
      //   icon: "si si-globe",
      //   type: "sub",
      //   active: false,
      //   role: ["admin", "user"],
      //   selected: false,
      //   children: [
      //     {
      //       path: `website`,
      //       type: "link",
      //       active: false,
      //       role: ["admin", "user"],
      //       selected: false,
      //       title: "Website",
      //     },
      //     {
      //       path: `landingpage`,
      //       type: "link",
      //       active: false,
      //       role: ["admin", "user"],
      //       selected: false,
      //       title: "Languages",
      //     },
      //   ],
      // },

      {
        title: "Landing Pages",
        icon: "pe-7s-car",
        type: "sub",
        active: false,
        role: ["admin", "user"],
        selected: false,
        children: [
          {
            path: `tour-details`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "All Landing Pages",
          },
          {
            path: `driverr/add`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Add Landing Page",
          },
        ],
      },
    ],
  },
  {
    menutitle: "Admin",
    Items: [
      {
        path: `users`,
        icon: "si si-people",
        type: "link",
        active: false,
        role: ["admin", "user"],
        selected: false,
        title: "Users",
      },
      {
        title: "Setting",
        icon: "ti-settings",
        type: "sub",
        active: false,
        role: ["admin", "user"],
        selected: false,
        children: [
          {
            path: `admin/country`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Countries",
          },
          {
            path: `admin/cities`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Cities",
          },
          {
            path: `admin/accommodation-types`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Accommodation Types",
          },
          {
            path: `admin/transportation-types`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Transportation Types",
          },
          {
            path: `admin/transportation-prices`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Transportation Prices",
          },
          {
            path: `admin/tourguide-prices`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Tourguide Prices",
          },
          {
            path: `admin/rooms-categories`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Rooms Categories",
          },
          {
            path: `admin/tour-header`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Tour Headers",
          },
          {
            path: `admin/tour-titles`,
            type: "link",
            active: false,
            role: ["admin", "user"],
            selected: false,
            title: "Tour Titles",
          },
        ],
      },
    ],
  },
];
